fix FacebookContentProvider
remove the xml node if no app id is provided since otherwise you will be
unable to install two apps with the facebook module but no app id. Fixes
error on install:

```
com.android.server.pm.PackageManagerException: Can't install because
provider name com.facebook.app.FacebookContentProvider (in package
{PACKAGE_NAME_1}) is already used by {PACKAGE_NAME_2}
```